package router

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"
)

// GenerateOptions controls zz_routes_gen.go emission.
type GenerateOptions struct {
	AppDir      string
	OutFile     string // default: zz_routes_gen.go in module/workdir
	PackageName string // default: main
}

// Generate writes a Go source file registering discovered routes.
func Generate(opts GenerateOptions) error {
	if opts.AppDir == "" {
		opts.AppDir = "app"
	}
	if opts.OutFile == "" {
		opts.OutFile = "zz_routes_gen.go"
	}
	if opts.PackageName == "" {
		opts.PackageName = "main"
	}

	routes, err := Discover(opts.AppDir)
	if err != nil {
		return err
	}

	var b strings.Builder
	b.WriteString("// Code generated by irmik generate; DO NOT EDIT.\n\n")
	b.WriteString("package " + opts.PackageName + "\n\n")
	needTime := false
	for _, rt := range routes {
		if rt.Meta.Revalidate > 0 {
			needTime = true
			break
		}
	}
	b.WriteString("import (\n")
	if needTime {
		b.WriteString("\t\"time\"\n\n")
	}
	b.WriteString("\t\"github.com/boracomet/go-irmik/irmik/meta\"\n")
	b.WriteString("\t\"github.com/boracomet/go-irmik/irmik/router\"\n")
	b.WriteString(")\n\n")
	b.WriteString("// IrmikRoutes is the generated route table from app/ discovery.\n")
	b.WriteString("var IrmikRoutes = []router.Route{\n")
	for _, rt := range routes {
		fmt.Fprintf(&b, "\t{\n")
		fmt.Fprintf(&b, "\t\tURLPath: %s,\n", strconv.Quote(rt.URLPath))
		fmt.Fprintf(&b, "\t\tRelDir:  %s,\n", strconv.Quote(rt.RelDir))
		fmt.Fprintf(&b, "\t\tPageFile: %s,\n", strconv.Quote(relOrAbs(opts.AppDir, rt.PageFile)))
		if len(rt.LayoutFiles) > 0 {
			b.WriteString("\t\tLayoutFiles: []string{\n")
			for _, lf := range rt.LayoutFiles {
				fmt.Fprintf(&b, "\t\t\t%s,\n", strconv.Quote(relOrAbs(opts.AppDir, lf)))
			}
			b.WriteString("\t\t},\n")
		}
		b.WriteString("\t\tMeta: meta.PageMeta{\n")
		fmt.Fprintf(&b, "\t\t\tMode:      meta.Mode(%s),\n", strconv.Quote(string(rt.Meta.Mode)))
		if rt.Meta.Revalidate > 0 {
			fmt.Fprintf(&b, "\t\t\tRevalidate: %s,\n", durationLit(rt.Meta.Revalidate))
		}
		if rt.Meta.Canonical != "" {
			fmt.Fprintf(&b, "\t\t\tCanonical: %s,\n", strconv.Quote(rt.Meta.Canonical))
		}
		if rt.Meta.Robots != "" {
			fmt.Fprintf(&b, "\t\t\tRobots: %s,\n", strconv.Quote(rt.Meta.Robots))
		}
		fmt.Fprintf(&b, "\t\t\tSitemap: %v,\n", rt.Meta.Sitemap)
		if rt.Meta.NoIndex {
			b.WriteString("\t\t\tNoIndex: true,\n")
		}
		b.WriteString("\t\t},\n")
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n\n")
	b.WriteString("// ApplyGeneratedRoutes replaces r's discovered routes with the generated table.\n")
	b.WriteString("// Call after router.New when using compile-time registration.\n")
	b.WriteString("func ApplyGeneratedRoutes(r *router.Router) {\n")
	b.WriteString("\tif r == nil {\n\t\treturn\n\t}\n")
	b.WriteString("\tr.SetRoutes(IrmikRoutes)\n")
	b.WriteString("}\n")

	if err := os.MkdirAll(filepath.Dir(opts.OutFile), 0o755); err != nil && filepath.Dir(opts.OutFile) != "." {
		return err
	}
	return os.WriteFile(opts.OutFile, []byte(b.String()), 0o644)
}

func relOrAbs(_ string, abs string) string {
	// Prefer path relative to cwd when possible for portable generated code.
	if rel, err := filepath.Rel(".", abs); err == nil && !strings.HasPrefix(rel, "..") {
		return filepath.ToSlash(rel)
	}
	return filepath.ToSlash(abs)
}

func durationLit(d time.Duration) string {
	if d%time.Hour == 0 && d >= time.Hour {
		return fmt.Sprintf("%d * time.Hour", int64(d/time.Hour))
	}
	if d%time.Minute == 0 && d >= time.Minute {
		return fmt.Sprintf("%d * time.Minute", int64(d/time.Minute))
	}
	if d%time.Second == 0 && d >= time.Second {
		return fmt.Sprintf("%d * time.Second", int64(d/time.Second))
	}
	return fmt.Sprintf("time.Duration(%d)", int64(d))
}

// SetRoutes replaces the in-memory route table (used by generated ApplyGeneratedRoutes).
func (r *Router) SetRoutes(routes []Route) {
	r.routes = append([]Route(nil), routes...)
}
